`rate` new aggr from Kibana 8.15
QuesmaOrg/quesma pull request #999
Opened 2024-11-14 12:09 UTC by trzysiek

2025-02-10 13:24 UTC, nablaone requested changes
We should use consts (our or from the `time` package) when we compute time/duration/intervals.

2025-02-10 13:24 UTC, nablaone commented on quesma/model/metrics_aggregations/rate.go
> +		someTime := time.UnixMilli(rows[0].Cols[0].Value.(int64)).Add(48 * time.Hour)
It may panic. We should check if the `Value` is `int64` before casting.

2025-02-10 13:24 UTC, nablaone commented on quesma/model/metrics_aggregations/rate.go
> +		return 1000
These can be constants. We can use `time.Duration` here.

2025-02-10 13:24 UTC, nablaone commented on quesma/model/metrics_aggregations/rate.go
> +		logger.WarnWithCtxAndThrottling(ctx, "rate", "unit", "invalid rate unit: %s", unit)
We can return an error here instead of returning a special `invalid`  value

2025-02-10 13:24 UTC, nablaone commented on quesma/model/metrics_aggregations/rate.go
> +		// theoretically unreachable
If it's not reachable, we can panic here.

2025-02-10 13:24 UTC, nablaone commented on quesma/queryparser/pancake_aggregation_parser_metrics.go
> +				logger.ErrorWithCtx(ctx).Msgf("unknown rate mode: %s", metricsAggr.mode)
We should return the error here.

2025-02-10 13:24 UTC, nablaone commented on quesma/model/metrics_aggregations/rate.go
> +	thirtyDaysInMs := int64(30 * 24 * 60 * 60 * 1000)
Here, we can extract the 'day' constant. `day` is referenced in a few places.

2025-03-10 14:43 UTC, trzysiek commented
I think I added all suggested changes. Please re-review.

2025-03-10 14:43 UTC, trzysiek commented
/run-integration-tests

2025-03-22 10:55 UTC, trzysiek commented
/run-it

2025-03-23 14:35 UTC, trzysiek commented
/run-it

2025-03-23 16:21 UTC, jakozaur reviewed
Great work, added some comments.

2025-03-23 16:21 UTC, jakozaur commented on platform/parsers/elastic_query_dsl/pancake_transformer.go
> +		fmt.Println(layer.nextBucketAggregation, layer.currentMetricAggregations)
I would remove `fmt.Println` before merging.

2025-03-23 16:21 UTC, jakozaur commented on platform/parsers/elastic_query_dsl/pancake_transformer.go
> +			dhInterval, ok := dateHistogram.Interval()
We should not mix two paterns and rather do same type of `if`:
```
			if dhInterval, ok := dateHistogram.Interval(); ok {		
```

2025-03-23 16:21 UTC, jakozaur commented on platform/parsers/elastic_query_dsl/pancake_json_rendering.go
> +	fmt.Println("kk model:", rows)
Remove `fmt.Println`.

2025-03-23 16:21 UTC, jakozaur commented on platform/parsers/elastic_query_dsl/pancake_json_rendering.go
> +			rate, _ := metric.queryType.(*metrics_aggregations.Rate)
You should instead add type inferring in switch:
```
switch queryType := metric.queryType.(type) {
```
and use it here.

2025-03-23 16:21 UTC, jakozaur commented on platform/parsers/elastic_query_dsl/pancake_json_rendering.go
> +				parentHistogramKey = fmt.Sprintf("%skey_0", parentHistogramColName)
Not sure if I like this logic, instead we should pass previous bucket aggregation, if exists and grab values from it.

2025-03-23 16:21 UTC, jakozaur commented on platform/model/metrics_aggregations/rate.go
> +				return fmt.Errorf("unexpected parameter %s found in IP Range params %v", paramName, params)
Please rename `IP Range` to `rate` here.

2025-03-24 09:23 UTC, trzysiek commented
/run-it

2025-03-26 08:25 UTC, trzysiek commented on platform/parsers/elastic_query_dsl/pancake_transformer.go
> +		fmt.Println(layer.nextBucketAggregation, layer.currentMetricAggregations)
sorry

2025-03-26 08:33 UTC, trzysiek commented
/run-it

2025-03-26 08:42 UTC, trzysiek commented
/run-it

2025-03-26 08:46 UTC, trzysiek commented
/run-it

2025-03-26 08:56 UTC, trzysiek commented
Please take a look once again, implemented all the suggestions

2025-03-26 09:56 UTC, trzysiek commented
/run-it

2025-03-26 11:12 UTC, merged